<a href="https://colab.research.google.com/github/brainmentorspvtltd/MAIT_FDP_2023/blob/main/NumpyPandasIntroduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
# array - collection of similar type of data
x = np.array([1,2,3,4,5])

In [7]:
np.array([2,3,6,8,6])

array([2, 3, 6, 8, 6])

In [8]:
np.array([2,3,6,8,6.4])

array([2. , 3. , 6. , 8. , 6.4])

In [9]:
np.array([2,3,6,8,6.5,"hello"])

array(['2', '3', '6', '8', '6.5', 'hello'], dtype='<U32')

In [10]:
np.array([2,3,6,8,6,True,4.5])

array([2. , 3. , 6. , 8. , 6. , 1. , 4.5])

In [11]:
x

array([1, 2, 3, 4, 5])

In [12]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
x = np.arange(1,21)

In [15]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
# generates a random number b/w 0 to 1
np.random.random()

0.2131212492937855

In [18]:
np.random.random(5)

array([0.2247328 , 0.33215141, 0.65154695, 0.36241007, 0.4601769 ])

In [20]:
np.random.random((5,5))

array([[0.38559161, 0.19951619, 0.53760469, 0.67597517, 0.40603841],
       [0.71244928, 0.00295622, 0.67951781, 0.51095461, 0.44651058],
       [0.04326333, 0.74708525, 0.01939309, 0.82095209, 0.20013324],
       [0.31214072, 0.58472123, 0.27407332, 0.11326616, 0.96957487],
       [0.10829245, 0.24639933, 0.65452493, 0.12473652, 0.59183707]])

In [29]:
np.random.randint(1,100,15)

array([75, 72, 80, 86, 79, 81, 73, 70, 20, 59, 18, 26, 55, 67, 92])

In [30]:
x = np.random.randint(1,100,(4,6))

In [31]:
x

array([[43, 51, 26, 77, 30, 60],
       [86, 28, 10, 18, 43, 97],
       [54, 44, 39, 99, 53, 41],
       [73, 89, 41, 98, 28, 73]])

In [32]:
x.shape

(4, 6)

In [33]:
x = np.random.randint(10,100,11)

In [34]:
# Indexing

In [35]:
x

array([49, 16, 26, 71, 36, 93, 49, 70, 33, 87, 95])

In [37]:
x[0]

49

In [38]:
x[6]

49

In [39]:
x[-1]

95

In [40]:
x[0:4]

array([49, 16, 26, 71])

In [41]:
x[4:9]

array([36, 93, 49, 70, 33])

In [42]:
x[5:20]

array([93, 49, 70, 33, 87, 95])

In [43]:
x[0:]

array([49, 16, 26, 71, 36, 93, 49, 70, 33, 87, 95])

In [44]:
x[:5]

array([49, 16, 26, 71, 36])

In [46]:
x[:]

array([49, 16, 26, 71, 36, 93, 49, 70, 33, 87, 95])

In [48]:
x[4:0:-1]

array([36, 71, 26, 16])

In [49]:
x[4::-1]

array([36, 71, 26, 16, 49])

In [51]:
x[-1:-5:-1]

array([95, 87, 33, 70])

In [52]:
x[::-1]

array([95, 87, 33, 70, 49, 93, 36, 71, 26, 16, 49])

In [53]:
x = np.random.randint(1,100,(6,4))

In [54]:
x

array([[69, 34, 93, 78],
       [82, 94, 86, 92],
       [31, 29, 96,  1],
       [43,  4, 77, 39],
       [ 1, 28, 99, 44],
       [14, 82, 66, 30]])

In [55]:
x[0]

array([69, 34, 93, 78])

In [56]:
x[0:2]

array([[69, 34, 93, 78],
       [82, 94, 86, 92]])

In [57]:
x[0][0]

69

In [58]:
# 0th column - : - all rows
x[:,0]

array([69, 82, 31, 43,  1, 14])

In [59]:
x[:,0:3]

array([[69, 34, 93],
       [82, 94, 86],
       [31, 29, 96],
       [43,  4, 77],
       [ 1, 28, 99],
       [14, 82, 66]])

In [60]:
x[2:4,0:2]

array([[31, 29],
       [43,  4]])

In [61]:
x.shape

(6, 4)

In [63]:
x.ndim

2

In [65]:
# convert data into 1D
x = x.flatten()

In [66]:
x

array([69, 34, 93, 78, 82, 94, 86, 92, 31, 29, 96,  1, 43,  4, 77, 39,  1,
       28, 99, 44, 14, 82, 66, 30])

In [67]:
np.sum(x)

1312

In [68]:
np.mean(x)

54.666666666666664

In [69]:
np.std(x)

32.518797982431984

In [70]:
np.var(x)

1057.4722222222224

In [72]:
x = np.reshape(x, (4,6))

In [73]:
x

array([[69, 34, 93, 78, 82, 94],
       [86, 92, 31, 29, 96,  1],
       [43,  4, 77, 39,  1, 28],
       [99, 44, 14, 82, 66, 30]])

In [74]:
x = np.reshape(x, (-1,4))

In [75]:
x

array([[69, 34, 93, 78],
       [82, 94, 86, 92],
       [31, 29, 96,  1],
       [43,  4, 77, 39],
       [ 1, 28, 99, 44],
       [14, 82, 66, 30]])

In [77]:
np.sum(x)

1312

In [78]:
# 0 - colwise
# 1 - rowwise
np.sum(x, axis=0)

array([240, 271, 517, 284])

In [79]:
np.sum(x, axis=1)

array([274, 354, 157, 163, 172, 192])

In [80]:
# np.sum(x[2]) - sum of 2nd row
# np.sum(x[:,2]) - sum of 2nd col

In [81]:
x

array([[69, 34, 93, 78],
       [82, 94, 86, 92],
       [31, 29, 96,  1],
       [43,  4, 77, 39],
       [ 1, 28, 99, 44],
       [14, 82, 66, 30]])

In [91]:
# np.vstack((x,np.array([[1,2,3,4]])))
np.vstack((x,np.random.randint(1,10,(1,4))))

array([[69, 34, 93, 78],
       [82, 94, 86, 92],
       [31, 29, 96,  1],
       [43,  4, 77, 39],
       [ 1, 28, 99, 44],
       [14, 82, 66, 30],
       [ 1,  5,  7,  2]])

In [92]:
# np.hstack((x,np.array([[1],[2],[3],[4],[5],[6]])))
np.hstack((x,np.random.randint(1,20,(6,1))))

array([[69, 34, 93, 78, 11],
       [82, 94, 86, 92, 16],
       [31, 29, 96,  1,  2],
       [43,  4, 77, 39, 10],
       [ 1, 28, 99, 44,  8],
       [14, 82, 66, 30,  4]])

In [94]:
# Pandas - Data Structure of Python used for Data Analysis
# 1D - Series
# 2D - DataFrame

In [95]:
import pandas as pd

names = ["John","Sam","Max","Mac","Nick","Andrew"]
age = [34,45,22,56,88,19]
series = pd.Series(age)

In [96]:
series

0    34
1    45
2    22
3    56
4    88
5    19
dtype: int64

In [97]:
series = pd.Series(age, index=names)

In [98]:
series

John      34
Sam       45
Max       22
Mac       56
Nick      88
Andrew    19
dtype: int64

In [99]:
series[0]

34

In [100]:
series['John']

34

In [101]:
data = {
    "names" : names,
    "age" : age
}
df = pd.DataFrame(data)

In [103]:
df

names  age
0    John   34
1     Sam   45
2     Max   22
3     Mac   56
4    Nick   88
5  Andrew   19

In [104]:
df["country"] = ["USA","IND","IND","USA","UK","UK"]

In [105]:
df

names  age country
0    John   34     USA
1     Sam   45     IND
2     Max   22     IND
3     Mac   56     USA
4    Nick   88      UK
5  Andrew   19      UK

In [106]:
df["names"]

0      John
1       Sam
2       Max
3       Mac
4      Nick
5    Andrew
Name: names, dtype: object

In [107]:
df[["names","age"]]

names  age
0    John   34
1     Sam   45
2     Max   22
3     Mac   56
4    Nick   88
5  Andrew   19

In [109]:
df.iloc[0]

names      John
age          34
country     USA
Name: 0, dtype: object

In [110]:
df.iloc[1]

names      Sam
age         45
country    IND
Name: 1, dtype: object

In [111]:
df.iloc[:,0]

0      John
1       Sam
2       Max
3       Mac
4      Nick
5    Andrew
Name: names, dtype: object

In [112]:
# return first 5 observations
df.head()

names  age country
0  John   34     USA
1   Sam   45     IND
2   Max   22     IND
3   Mac   56     USA
4  Nick   88      UK

In [113]:
df.head(3)

names  age country
0  John   34     USA
1   Sam   45     IND
2   Max   22     IND